### ISSUE TITLE
Mouseover

### ISSUE THREAD

**Issue by Rolh01** [luskanek/CRF#5]
Hey! In the readme file say: "- Mouseover macros implemented by other addons are supported"
But for me it isnt work any vanilla wow mouseover addon.

Can you help me with this problem?
How should I solve this?

Thanks in advance!

**Comment by luskanek** [comment]
Are you using a macro addon that supports mouseover macros? The default Vanilla macro system doesn't support mouseover macros.

**Comment by Rolh01** [comment]
Sure, I am using addons for it. (Clique, ClassicMouseover).
And this addons work with the original blizzard unit frames.
What it takes to be work the CRF addon with these (Clique, ClassicMouseover) addons?

**Comment by luskanek** [comment]
Clique doesn't work out of the box, I will have to look into supporting it. I haven't tested ClassicMouseover, don't know that addon. Other more popular like SuperMacro or Roid Macros work without issues.
