### ISSUE TITLE
Range

### ISSUE THREAD

**Issue by kzaer** [luskanek/CRF#6]
Is there way to show correctly show who is in range of healing spells(40yd) and who is not? Players fade out before they are out of range atm
Dont know how to change this

**Comment by luskanek** [comment]
No way to change this, it is hardcoded to ~30 yards. I might change it in the future.

**Comment by kzaer** [comment]
Oh please do change it, or even better add a way to change it how player
wants.

Couple more ideas:
If you have the time you could add ways to customize further the buffs and
debuffs too.
And maybe couple presets? I like to keep the bars bigger when in 5man
group, thats size is ofc not feasable in 40man.

This addon is my life, just excelent. Thank you.

Arto N

ti 19. jouluk. 2023 klo 21.00 Lukáš ***@***.***> kirjoitti:
